sudo: false
dist: trusty
language: node_js
node_js: node

cache:
  directories:
    - node_modules

addons:
  firefox: latest
  chrome: stable

script:
  - if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" ]]; then
      npm run test:modern && npm run test:legacy;
    else
      npm test;
    fi

after_success:
  - "cat ${TRAVIS_BUILD_DIR}/coverage/lcov.info | coveralls"
